# Generated by Django 5.0 on 2023-12-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sort', models.CharField(max_length=255, verbose_name='Sort')),
                ('designer', models.CharField(max_length=255, verbose_name='Designer')),
                ('first_flight', models.CharField(max_length=255, verbose_name='First flight')),
                ('introduct', models.CharField(max_length=255, verbose_name='Introduction to service')),
                ('prod_range', models.CharField(max_length=255, verbose_name='Production range')),
                ('number_of_production', models.CharField(max_length=255, verbose_name='Number of production')),
                ('unit_cost', models.CharField(max_length=255, verbose_name='Unit cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plane',
                'verbose_name_plural': 'Planes',
                'ordering': ('-created_at',),
            },
        ),
    ]
